name: Trigger Digital Garden Deploy

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PARENT_REPO_PAT }}" \
            https://api.github.com/repos/ivktac/digital-garden/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
